language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

os:
    - linux

env:
    global:
        - PYTHON_VERSION=3.6
        - SETUP_XVFB=True
        - CONDA_DEPENDENCIES='jupyter notebook ipython runipy'
        - GH_REF: github.com/astropy/astropy-tutorials.git
        - secure: "NBZlEg//sDYvJikqXESLsx/WA1Nj7fAH2mJfI8ZVMnolvyjJuLdEMxxEYFP8t6U/iieSSrgUkgP94yy5Oq6iJRjj7ThGCdcjgvgWTQCzoQgEVDc5SzdJGyGs30VC+8t7GTobzMe086HX16SJRvsIumqXdmRcJjAdMCyhMUxLoUg="

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
    - conda env create -f conda-environment.yml -n tutorials
    - source activate tutorials
    - python prepare_deploy.py run

deploy:
    provider: script
    script: ./travis_deploy
    on:
        repo: astropy/astropy-tutorials
        branch: master
