language: python

os:
    - linux

env:
    global:
        - NUMPY_VERSION=1.9
        - PYTHON_VERSION=2.7

install:
    - source .travis/setup_environment.sh

script:
    - python prepare_deploy.py run

