title = 'therealzoidberg Notebooks'
description = 'A space for Astronomy Notebooks'
keywords = ['stsci', 'therealzoidberg', 'jupyter', 'notebooks', 'astronomy']
author = 'therealzoidberg'
maintainer = 'Michael Gough'
default_locale = 'en'
website_base_url = 'https://therealzoidberg.github.io/dat_pyinthesky'
index_title = 'therealzoidberg dat_pyinthesky Index'
locale = 'en'
notebook_title = 'JDAT Notebook'
notebook_keywords = ['stsci', 'therealzoidberg', 'jupyter', 'notebooks', 'astronomy']
notebook_description = 'A space for Astronomy Notebooks'
